// Endpoints
export const AUTH_ENDPOINTS = {
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  VERIFY: "/auth/verify",
  FORGOT: "/auth/forgot-password",
  RESET: "/auth/reset-password",
  LOGOUT: "/auth/logout",
} as const;

export const USER_ENDPOINTS = {
  ME: "/users/me",
  LINKED_CHILDREN: "/users/me/linked-children",
  LINKED_CHILD_HISTORY: (childId: number | string) => `/users/me/linked-children/${childId}/history`,
  LINKED_CHILD_BADGES: (childId: number | string) => `/users/me/linked-children/${childId}/badges`,
  UPDATE_PROFILE: "/users/update-profile",
  CHANGE_PASSWORD: "/users/change-password",
  ONBOARDING: "/users/me/onboarding",
  GAME_REFLEX_SETTINGS: (gameId: number | string) => `/users/games/${gameId}/reflex-settings`,
  AVAILABLE_GAMES: "/users/games/available",
  GAME_SESSIONS: "/users/game-sessions",
  PROGRESS_OVERVIEW: "/users/progress/overview",
  BADGES_OVERVIEW: "/users/badges/overview",
  BADGE_CLAIM: (badgeId: number | string) => `/users/badges/${badgeId}/claim`,
  REWARDS_OVERVIEW: "/users/rewards/overview",
  REWARD_CLAIM: (rewardId: number | string) => `/users/rewards/${rewardId}/claim`,
  HISTORY_SESSIONS: "/users/history/sessions",
  LEADERBOARD_SOLO: "/users/leaderboard/solo",
  LEADERBOARD_SOLO_SCOPED: (scope: string) => `/users/leaderboard/solo/scoped?scope=${encodeURIComponent(scope)}`,
  LEADERBOARD_ME_RANKS: "/users/leaderboard/me/ranks",
  ROOMS_CREATE: "/users/rooms/create",
  ROOMS_JOIN: "/users/rooms/join",
  ROOM_BY_CODE: (roomCode: string) => `/users/rooms/${roomCode}`,
  ROOM_RESULT: (roomCode: string, gameId: number | string) =>
    `/users/rooms/${roomCode}/result?gameId=${encodeURIComponent(String(gameId))}`,
  ROOM_READY: (roomCode: string) => `/users/rooms/${roomCode}/ready`,
  ROOM_START: (roomCode: string) => `/users/rooms/${roomCode}/start`,
  GAME_QUIZ_QUESTIONS: (gameId: number | string) => `/users/games/${gameId}/quiz-questions`,
  GAME_MEMORY_CARDS: (gameId: number | string) => `/users/games/${gameId}/memory-cards`,
  GAME_LOGIC_PUZZLES: (gameId: number | string) => `/users/games/${gameId}/logic-puzzles`,
  RECLAMATIONS: "/users/reclamations",
} as const;

export const ADMIN_ENDPOINTS = {
  USERS: "/admin/users",
  USER_BY_ID: (id: number | string) => `/admin/users/${id}`,
  SUSPEND_USER: (id: number | string) => `/admin/users/suspend/${id}`,
  REACTIVATE_USER: (id: number | string) => `/admin/users/reactivate/${id}`,
  USER_ROLE: (id: number | string) => `/admin/users/${id}/change-role`,
  USER_PARENT_LINK: (id: number | string) => `/admin/users/${id}/parent-link`,
  ACTIVE_SESSIONS_COUNT: "/admin/users/sessions/active-count",
  SCORING_DISTRIBUTION: "/admin/users/scoring-distribution",
  STATISTICS_SESSIONS_BY_DAY: "/admin/statistics/sessions-by-day",
  STATISTICS_RECENT_ACTIVITY: "/admin/statistics/recent-activity",
  STATISTICS_OVERVIEW: "/admin/statistics/overview",
  GAMES: "/admin/games",
  GAME_BY_ID: (id: number | string) => `/admin/games/${id}`,
  GAME_AI_REVIEW: (id: number | string) => `/admin/games/${id}/ai-review`,
  GAME_STATUS: (id: number | string) => `/admin/games/${id}/status`,
  GAME_QUESTIONS: (id: number | string) => `/admin/games/${id}/questions`,

  GAME_MEMORY_CARDS: (id: number | string) => `/admin/games/${id}/memory-cards`,
  GAME_LOGIC_PUZZLES: (id: number | string) => `/admin/games/${id}/logic-puzzles`,
  GAME_REFLEX_SETTINGS: (id: number | string) => `/admin/games/${id}/reflex-settings`,
  BADGES: "/admin/badges",
  BADGE_BY_ID: (id: number | string) => `/admin/badges/${id}`,
  RECLAMATIONS: "/admin/reclamations",
  RECLAMATION_BY_ID: (id: number | string) => `/admin/reclamations/${id}`,
  RECLAMATIONS_PENDING_COUNT: "/admin/reclamations/pending-count",
} as const;

export const EDUCATOR_ENDPOINTS = {
  GAMES: "/educator/games",
  GAME_BY_ID: (id: number | string) => `/educator/games/${id}`,
  GAME_COVER_GENERATE: (id: number | string) => `/educator/games/${id}/cover/generate`,
  GAME_COVER_DELETE: (id: number | string) => `/educator/games/${id}/cover`,
  GAME_COVER_UPLOAD: (id: number | string) => `/educator/games/${id}/cover/upload`,
  GAME_COVER_GENERATE_PREVIEW: "/educator/games/cover/generate-preview",
  GAME_SUBMIT: (id: number | string) => `/educator/games/${id}/submit`,
  QUESTIONS: "/educator/questions",
  QUESTION_BY_ID: (id: number | string) => `/educator/questions/${id}`,
  QUESTION_MEDIA_UPLOAD: (id: number | string) => `/educator/questions/${id}/media/upload`,
  QUESTION_PROMPT_AUDIO_UPLOAD: (id: number | string) => `/educator/questions/${id}/prompt-audio/upload`,
  QUESTIONS_AI_GENERATE_PREVIEW: "/educator/questions/ai/generate-preview",
  LOGIC_PUZZLES: "/educator/logic-puzzles",
  REFLEX_SETTINGS: "/educator/reflex-settings",
  MEMORY_CARDS: "/educator/memory-cards",
  MEMORY_CARD_BY_ID: (id: number | string) => `/educator/memory-cards/${id}`,
  DASHBOARD_STATS: "/educator/dashboard/stats",
  LEARNING_STATS: "/educator/statistics/learning",
  VOICE_SERIES: "/educator/voice/series",
  VOICE_SERIES_BY_ID: (id: number | string) => `/educator/voice/series/${id}`,
  VOICE_SERIES_PUBLISH: (id: number | string) => `/educator/voice/series/${id}/publish`,
  VOICE_SERIES_ARCHIVE: (id: number | string) => `/educator/voice/series/${id}/archive`,
  VOICE_PROMPTS: "/educator/voice/prompts",
  VOICE_PROMPT_BY_ID: (id: number | string) => `/educator/voice/prompts/${id}`,
} as const;

export const PLAYER_VOICE_ENDPOINTS = {
  SERIES: "/player/voice/series",
  SERIES_BY_ID: (id: number | string) => `/player/voice/series/${id}`,
  SESSION_START: "/player/voice/sessions/start",
  EVALUATE: "/player/voice/evaluate",
  SESSION_COMPLETE: (id: number | string) => `/player/voice/sessions/${id}/complete`,
  HISTORY: "/player/voice/history",
} as const;

export const SPONSOR_ENDPOINTS = {
  DASHBOARD_STATS: "/sponsor/dashboard/stats",
  PUBLICITES: "/sponsor/publicites",
  PUBLICITE_BY_ID: (id: number | string) => `/sponsor/publicites/${id}`,
  PUBLICITE_STATUS: (id: number | string) => `/sponsor/publicites/${id}/status`,
  RECOMPENSES: "/sponsor/recompenses",
  RECOMPENSE_BY_ID: (id: number | string) => `/sponsor/recompenses/${id}`,
  RECOMPENSE_STATUS: (id: number | string) => `/sponsor/recompenses/${id}/status`,
  REWARD_REQUESTS: "/sponsor/reward-requests",
  REWARD_REQUEST_STATUS: (id: number | string) => `/sponsor/reward-requests/${id}/status`,
} as const;
