// Endpoints
export const AUTH_ENDPOINTS = {
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  VERIFY: "/auth/verify",
  FORGOT: "/auth/forgot-password",
  RESET: "/auth/reset-password",
  LOGOUT: "/auth/logout",
} as const;

export const USER_ENDPOINTS = {
  ME: "/users/me",
  UPDATE_PROFILE: "/users/update-profile",
  CHANGE_PASSWORD: "/users/change-password",
  ONBOARDING: "/users/me/onboarding",
  GAME_REFLEX_SETTINGS: (gameId: number | string) => `/users/games/${gameId}/reflex-settings`,
  AVAILABLE_GAMES: "/users/games/available",
  GAME_SESSIONS: "/users/game-sessions",
  PROGRESS_OVERVIEW: "/users/progress/overview",
  BADGES_OVERVIEW: "/users/badges/overview",
  BADGE_CLAIM: (badgeId: number | string) => `/users/badges/${badgeId}/claim`,
  REWARDS_OVERVIEW: "/users/rewards/overview",
  REWARD_CLAIM: (rewardId: number | string) => `/users/rewards/${rewardId}/claim`,
  HISTORY_SESSIONS: "/users/history/sessions",
  LEADERBOARD_SOLO: "/users/leaderboard/solo",
  LEADERBOARD_TEAM: "/users/leaderboard/team",
  ROOMS_CREATE: "/users/rooms/create",
  ROOMS_JOIN: "/users/rooms/join",
  ROOM_BY_CODE: (roomCode: string) => `/users/rooms/${roomCode}`,
  ROOM_READY: (roomCode: string) => `/users/rooms/${roomCode}/ready`,
  ROOM_START: (roomCode: string) => `/users/rooms/${roomCode}/start`,
  ROOM_TEAM_NAME: (roomCode: string) => `/users/rooms/${roomCode}/team-name`,
  GAME_QUIZ_QUESTIONS: (gameId: number | string) => `/users/games/${gameId}/quiz-questions`,
  GAME_MEMORY_CARDS: (gameId: number | string) => `/users/games/${gameId}/memory-cards`,
  GAME_LOGIC_PUZZLES: (gameId: number | string) => `/users/games/${gameId}/logic-puzzles`,
} as const;

export const ADMIN_ENDPOINTS = {
  USERS: "/admin/users",
  USER_BY_ID: (id: number | string) => `/admin/users/${id}`,
  SUSPEND_USER: (id: number | string) => `/admin/users/suspend/${id}`,
  REACTIVATE_USER: (id: number | string) => `/admin/users/reactivate/${id}`,
  USER_ROLE: (id: number | string) => `/admin/users/${id}/change-role`,
  ACTIVE_SESSIONS_COUNT: "/admin/users/sessions/active-count",
  SCORING_DISTRIBUTION: "/admin/users/scoring-distribution",
  GAMES: "/admin/games",
  GAME_BY_ID: (id: number | string) => `/admin/games/${id}`,
  GAME_AI_REVIEW: (id: number | string) => `/admin/games/${id}/ai-review`,
  GAME_STATUS: (id: number | string) => `/admin/games/${id}/status`,
  GAME_QUESTIONS: (id: number | string) => `/admin/games/${id}/questions`,

  GAME_MEMORY_CARDS: (id: number | string) => `/admin/games/${id}/memory-cards`,
  BADGES: "/admin/badges",
  BADGE_BY_ID: (id: number | string) => `/admin/badges/${id}`,
} as const;

export const EDUCATOR_ENDPOINTS = {
  GAMES: "/educator/games",
  GAME_BY_ID: (id: number | string) => `/educator/games/${id}`,
  GAME_COVER_GENERATE: (id: number | string) => `/educator/games/${id}/cover/generate`,
  GAME_COVER_DELETE: (id: number | string) => `/educator/games/${id}/cover`,
  GAME_COVER_UPLOAD: (id: number | string) => `/educator/games/${id}/cover/upload`,
  GAME_COVER_GENERATE_PREVIEW: "/educator/games/cover/generate-preview",
  GAME_SUBMIT: (id: number | string) => `/educator/games/${id}/submit`,
  QUESTIONS: "/educator/questions",
  QUESTION_BY_ID: (id: number | string) => `/educator/questions/${id}`,
  QUESTIONS_AI_GENERATE_PREVIEW: "/educator/questions/ai/generate-preview",
  LOGIC_PUZZLES: "/educator/logic-puzzles",
  REFLEX_SETTINGS: "/educator/reflex-settings",
  REFLEX_SETTINGS_AI_GENERATE_PREVIEW: "/educator/reflex-settings/ai/generate-preview",
  MEMORY_CARDS: "/educator/memory-cards",
  MEMORY_CARD_BY_ID: (id: number | string) => `/educator/memory-cards/${id}`,
  DASHBOARD_STATS: "/educator/dashboard/stats",
} as const;

export const SPONSOR_ENDPOINTS = {
  DASHBOARD_STATS: "/sponsor/dashboard/stats",
  PUBLICITES: "/sponsor/publicites",
  PUBLICITE_BY_ID: (id: number | string) => `/sponsor/publicites/${id}`,
  PUBLICITE_STATUS: (id: number | string) => `/sponsor/publicites/${id}/status`,
  RECOMPENSES: "/sponsor/recompenses",
  RECOMPENSE_BY_ID: (id: number | string) => `/sponsor/recompenses/${id}`,
  RECOMPENSE_STATUS: (id: number | string) => `/sponsor/recompenses/${id}/status`,
  REWARD_REQUESTS: "/sponsor/reward-requests",
  REWARD_REQUEST_STATUS: (id: number | string) => `/sponsor/reward-requests/${id}/status`,
} as const;
