# ===========================================
# DATABASE CONFIGURATION (PostgreSQL)
# ===========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/edugame
spring.datasource.username=postgres
spring.datasource.password=mouadh123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# JPA / HIBERNATE
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===========================================
# SERVER
# ===========================================
server.port=8081
# Inscription avec photo (base64) peut dépasser 2 Mo
server.tomcat.max-http-form-post-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===========================================
# JWT CONFIGURATION
# ===========================================
jwt.secret=MySecureJWTSecretKey2024AuthBackendApplication!
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Timeout pour l'envoi d'email (évite les blocages)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



# ===========================================
# APP CONFIGURATION
# ===========================================
app.frontend-url=http://localhost:3000